### ISSUE TITLE
Change keyword "markdownlint-rules" to "markdownlint-rule"

### ISSUE THREAD

**Issue by DavidAnson** [syseleven/markdownlint-rules-grav-pages#1]
This is my fault, sorry. I changed my mind and decided the keyword should be singular. If you'd like your package to be found by the keyword link from https://github.com/DavidAnson/markdownlint/blob/master/doc/CustomRules.md, please change the keyword plurality with your next publish.

Again, sorry for the change.

PS - It's super cool to see what you've done here - nice!!

**Comment by bashofmann** [comment]
Fixed. Thanks for the hint :)
